### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Tomosuke0930** [Tomosuke0930/JP_Lottery#5]
1. Reproduce my Stack
・Frontend
- [x] Creating Frontend
- [x] Implementing Logic / Login !!!
- [x] Add types 
・Core
-----------------------------
- [x] Chainlink Contract Tests
- [x] Add original contracts

2. Add original contents !

**Comment by Tomosuke0930** [comment]
Finished! Go to Next Step
